name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.16.0' # Matches release.yml

      - name: Check Formatting
        run: zig fmt --check --exclude src/core/assets/templates src/ build.zig

      - name: Build All Targets
        # We ensure that changes don't break the cross-compilation matrix
        run: zig build

      - name: Run Native Tests
        # We run the internal test suite
        run: zig build test
